### ISSUE TITLE
Is this based in yeoman 1.3.4 or 1.4.0 ?

### ISSUE THREAD

**Issue by NPrice99** [giuleon/AutomatedDeploymentForSPFx#1]
Hi
Does this script assume Yeoman 1.3.4 scaffolding (ie the json and javascript is separate from the sppkg file) or yeoman 1.4.0 (where the json and javascript is included in the sppkg file) ?

Thanks

Nigel

**Comment by giuleon** [comment]
Hi Nigel,

if you plan to host your bundle on Office 365 CDN, the script works independently from the generator version, it is compatible with all versions at the moment.

**Comment by NPrice99** [comment]
Hi
Going from 1.3.4 to 1.4.0 means that you  go from react 14.0 to 15.0 this is where the compilation error occurs.

Regards

Nigel

**Comment by giuleon** [comment]
Hi,

Check this demo:
https://github.com/giuleon/spfx-almapi

I used yeoman 1.4.0 and everything works fine with the powershell scripts

**Comment by giuleon** [comment]
Closed due to no feedback.
